using System;
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;

[module: SkipLocalsInit]

namespace Microsoft.Maui.Graphics.Benchmarks
{
	[DisassemblyDiagnoser]
	public class ColorBenchmarker
	{
		[Benchmark]
		public Color SpanBlack() => GetNamedColorSpan("Black");
		[Benchmark]
		public Color StringBlack() => GetNamedColorString("Black");

		[Benchmark]
		public Color SpanLightGoldenrodYellowk() => GetNamedColorSpan("LightGoldenrodYellow");
		[Benchmark]
		public Color StringLightGoldenrodYellow() => GetNamedColorString("LightGoldenrodYellow");

		static Color GetNamedColorSpan(ReadOnlySpan<char> value)
		{
			// the longest built-in Color's name is much lower than this check, so we should not allocate here in a typical usage
			Span<char> loweredValue = value.Length <= 128 ? stackalloc char[value.Length] : new char[value.Length];

			int charsWritten = value.ToLowerInvariant(loweredValue);

			return loweredValue switch
			{
				"default" => default,
				"aliceblue" => Colors.AliceBlue,
				"antiquewhite" => Colors.AntiqueWhite,
				"aqua" => Colors.Aqua,
				"aquamarine" => Colors.Aquamarine,
				"azure" => Colors.Azure,
				"beige" => Colors.Beige,
				"bisque" => Colors.Bisque,
				"black" => Colors.Black,
				"blanchedalmond" => Colors.BlanchedAlmond,
				"blue" => Colors.Blue,
				"blueviolet" => Colors.BlueViolet,
				"brown" => Colors.Brown,
				"burlywood" => Colors.BurlyWood,
				"cadetblue" => Colors.CadetBlue,
				"chartreuse" => Colors.Chartreuse,
				"chocolate" => Colors.Chocolate,
				"coral" => Colors.Coral,
				"cornflowerblue" => Colors.CornflowerBlue,
				"cornsilk" => Colors.Cornsilk,
				"crimson" => Colors.Crimson,
				"cyan" => Colors.Cyan,
				"darkblue" => Colors.DarkBlue,
				"darkcyan" => Colors.DarkCyan,
				"darkgoldenrod" => Colors.DarkGoldenrod,
				"darkgray" => Colors.DarkGray,
				"darkgreen" => Colors.DarkGreen,
				"darkgrey" => Colors.DarkGrey,
				"darkkhaki" => Colors.DarkKhaki,
				"darkmagenta" => Colors.DarkMagenta,
				"darkolivegreen" => Colors.DarkOliveGreen,
				"darkorange" => Colors.DarkOrange,
				"darkorchid" => Colors.DarkOrchid,
				"darkred" => Colors.DarkRed,
				"darksalmon" => Colors.DarkSalmon,
				"darkseagreen" => Colors.DarkSeaGreen,
				"darkslateblue" => Colors.DarkSlateBlue,
				"darkslategray" => Colors.DarkSlateGray,
				"darkslategrey" => Colors.DarkSlateGrey,
				"darkturquoise" => Colors.DarkTurquoise,
				"darkviolet" => Colors.DarkViolet,
				"deeppink" => Colors.DeepPink,
				"deepskyblue" => Colors.DeepSkyBlue,
				"dimgray" => Colors.DimGray,
				"dimgrey" => Colors.DimGrey,
				"dodgerblue" => Colors.DodgerBlue,
				"firebrick" => Colors.Firebrick,
				"floralwhite" => Colors.FloralWhite,
				"forestgreen" => Colors.ForestGreen,
				"fuchsia" => Colors.Fuchsia,
				"gainsboro" => Colors.Gainsboro,
				"ghostwhite" => Colors.GhostWhite,
				"gold" => Colors.Gold,
				"goldenrod" => Colors.Goldenrod,
				"gray" => Colors.Gray,
				"green" => Colors.Green,
				"grey" => Colors.Grey,
				"greenyellow" => Colors.GreenYellow,
				"honeydew" => Colors.Honeydew,
				"hotpink" => Colors.HotPink,
				"indianred" => Colors.IndianRed,
				"indigo" => Colors.Indigo,
				"ivory" => Colors.Ivory,
				"khaki" => Colors.Khaki,
				"lavender" => Colors.Lavender,
				"lavenderblush" => Colors.LavenderBlush,
				"lawngreen" => Colors.LawnGreen,
				"lemonchiffon" => Colors.LemonChiffon,
				"lightblue" => Colors.LightBlue,
				"lightcoral" => Colors.LightCoral,
				"lightcyan" => Colors.LightCyan,
				"lightgoldenrodyellow" => Colors.LightGoldenrodYellow,
				"lightgrey" => Colors.LightGrey,
				"lightgray" => Colors.LightGray,
				"lightgreen" => Colors.LightGreen,
				"lightpink" => Colors.LightPink,
				"lightsalmon" => Colors.LightSalmon,
				"lightseagreen" => Colors.LightSeaGreen,
				"lightskyblue" => Colors.LightSkyBlue,
				"lightslategray" => Colors.LightSlateGray,
				"lightslategrey" => Colors.LightSlateGrey,
				"lightsteelblue" => Colors.LightSteelBlue,
				"lightyellow" => Colors.LightYellow,
				"lime" => Colors.Lime,
				"limegreen" => Colors.LimeGreen,
				"linen" => Colors.Linen,
				"magenta" => Colors.Magenta,
				"maroon" => Colors.Maroon,
				"mediumaquamarine" => Colors.MediumAquamarine,
				"mediumblue" => Colors.MediumBlue,
				"mediumorchid" => Colors.MediumOrchid,
				"mediumpurple" => Colors.MediumPurple,
				"mediumseagreen" => Colors.MediumSeaGreen,
				"mediumslateblue" => Colors.MediumSlateBlue,
				"mediumspringgreen" => Colors.MediumSpringGreen,
				"mediumturquoise" => Colors.MediumTurquoise,
				"mediumvioletred" => Colors.MediumVioletRed,
				"midnightblue" => Colors.MidnightBlue,
				"mintcream" => Colors.MintCream,
				"mistyrose" => Colors.MistyRose,
				"moccasin" => Colors.Moccasin,
				"navajowhite" => Colors.NavajoWhite,
				"navy" => Colors.Navy,
				"oldlace" => Colors.OldLace,
				"olive" => Colors.Olive,
				"olivedrab" => Colors.OliveDrab,
				"orange" => Colors.Orange,
				"orangered" => Colors.OrangeRed,
				"orchid" => Colors.Orchid,
				"palegoldenrod" => Colors.PaleGoldenrod,
				"palegreen" => Colors.PaleGreen,
				"paleturquoise" => Colors.PaleTurquoise,
				"palevioletred" => Colors.PaleVioletRed,
				"papayawhip" => Colors.PapayaWhip,
				"peachpuff" => Colors.PeachPuff,
				"peru" => Colors.Peru,
				"pink" => Colors.Pink,
				"plum" => Colors.Plum,
				"powderblue" => Colors.PowderBlue,
				"purple" => Colors.Purple,
				"red" => Colors.Red,
				"rosybrown" => Colors.RosyBrown,
				"royalblue" => Colors.RoyalBlue,
				"saddlebrown" => Colors.SaddleBrown,
				"salmon" => Colors.Salmon,
				"sandybrown" => Colors.SandyBrown,
				"seagreen" => Colors.SeaGreen,
				"seashell" => Colors.SeaShell,
				"sienna" => Colors.Sienna,
				"silver" => Colors.Silver,
				"skyblue" => Colors.SkyBlue,
				"slateblue" => Colors.SlateBlue,
				"slategray" => Colors.SlateGray,
				"slategrey" => Colors.SlateGrey,
				"snow" => Colors.Snow,
				"springgreen" => Colors.SpringGreen,
				"steelblue" => Colors.SteelBlue,
				"tan" => Colors.Tan,
				"teal" => Colors.Teal,
				"thistle" => Colors.Thistle,
				"tomato" => Colors.Tomato,
				"transparent" => Colors.Transparent,
				"turquoise" => Colors.Turquoise,
				"violet" => Colors.Violet,
				"wheat" => Colors.Wheat,
				"white" => Colors.White,
				"whitesmoke" => Colors.WhiteSmoke,
				"yellow" => Colors.Yellow,
				"yellowgreen" => Colors.YellowGreen,
				_ => null
			};
		}

		static Color GetNamedColorString(ReadOnlySpan<char> value)
		{
			// the longest built-in Color's name is much lower than this check, so we should not allocate here in a typical usage
			Span<char> loweredValue = value.Length <= 128 ? stackalloc char[value.Length] : new char[value.Length];

			int charsWritten = value.ToLowerInvariant(loweredValue);

			// this should use the C# feature https://github.com/dotnet/csharplang/issues/1881, when it is available
			// for now, we need to allocate the lowered string
			return loweredValue.ToString() switch
			{
				"default" => default,
				"aliceblue" => Colors.AliceBlue,
				"antiquewhite" => Colors.AntiqueWhite,
				"aqua" => Colors.Aqua,
				"aquamarine" => Colors.Aquamarine,
				"azure" => Colors.Azure,
				"beige" => Colors.Beige,
				"bisque" => Colors.Bisque,
				"black" => Colors.Black,
				"blanchedalmond" => Colors.BlanchedAlmond,
				"blue" => Colors.Blue,
				"blueviolet" => Colors.BlueViolet,
				"brown" => Colors.Brown,
				"burlywood" => Colors.BurlyWood,
				"cadetblue" => Colors.CadetBlue,
				"chartreuse" => Colors.Chartreuse,
				"chocolate" => Colors.Chocolate,
				"coral" => Colors.Coral,
				"cornflowerblue" => Colors.CornflowerBlue,
				"cornsilk" => Colors.Cornsilk,
				"crimson" => Colors.Crimson,
				"cyan" => Colors.Cyan,
				"darkblue" => Colors.DarkBlue,
				"darkcyan" => Colors.DarkCyan,
				"darkgoldenrod" => Colors.DarkGoldenrod,
				"darkgray" => Colors.DarkGray,
				"darkgreen" => Colors.DarkGreen,
				"darkgrey" => Colors.DarkGrey,
				"darkkhaki" => Colors.DarkKhaki,
				"darkmagenta" => Colors.DarkMagenta,
				"darkolivegreen" => Colors.DarkOliveGreen,
				"darkorange" => Colors.DarkOrange,
				"darkorchid" => Colors.DarkOrchid,
				"darkred" => Colors.DarkRed,
				"darksalmon" => Colors.DarkSalmon,
				"darkseagreen" => Colors.DarkSeaGreen,
				"darkslateblue" => Colors.DarkSlateBlue,
				"darkslategray" => Colors.DarkSlateGray,
				"darkslategrey" => Colors.DarkSlateGrey,
				"darkturquoise" => Colors.DarkTurquoise,
				"darkviolet" => Colors.DarkViolet,
				"deeppink" => Colors.DeepPink,
				"deepskyblue" => Colors.DeepSkyBlue,
				"dimgray" => Colors.DimGray,
				"dimgrey" => Colors.DimGrey,
				"dodgerblue" => Colors.DodgerBlue,
				"firebrick" => Colors.Firebrick,
				"floralwhite" => Colors.FloralWhite,
				"forestgreen" => Colors.ForestGreen,
				"fuchsia" => Colors.Fuchsia,
				"gainsboro" => Colors.Gainsboro,
				"ghostwhite" => Colors.GhostWhite,
				"gold" => Colors.Gold,
				"goldenrod" => Colors.Goldenrod,
				"gray" => Colors.Gray,
				"green" => Colors.Green,
				"grey" => Colors.Grey,
				"greenyellow" => Colors.GreenYellow,
				"honeydew" => Colors.Honeydew,
				"hotpink" => Colors.HotPink,
				"indianred" => Colors.IndianRed,
				"indigo" => Colors.Indigo,
				"ivory" => Colors.Ivory,
				"khaki" => Colors.Khaki,
				"lavender" => Colors.Lavender,
				"lavenderblush" => Colors.LavenderBlush,
				"lawngreen" => Colors.LawnGreen,
				"lemonchiffon" => Colors.LemonChiffon,
				"lightblue" => Colors.LightBlue,
				"lightcoral" => Colors.LightCoral,
				"lightcyan" => Colors.LightCyan,
				"lightgoldenrodyellow" => Colors.LightGoldenrodYellow,
				"lightgrey" => Colors.LightGrey,
				"lightgray" => Colors.LightGray,
				"lightgreen" => Colors.LightGreen,
				"lightpink" => Colors.LightPink,
				"lightsalmon" => Colors.LightSalmon,
				"lightseagreen" => Colors.LightSeaGreen,
				"lightskyblue" => Colors.LightSkyBlue,
				"lightslategray" => Colors.LightSlateGray,
				"lightslategrey" => Colors.LightSlateGrey,
				"lightsteelblue" => Colors.LightSteelBlue,
				"lightyellow" => Colors.LightYellow,
				"lime" => Colors.Lime,
				"limegreen" => Colors.LimeGreen,
				"linen" => Colors.Linen,
				"magenta" => Colors.Magenta,
				"maroon" => Colors.Maroon,
				"mediumaquamarine" => Colors.MediumAquamarine,
				"mediumblue" => Colors.MediumBlue,
				"mediumorchid" => Colors.MediumOrchid,
				"mediumpurple" => Colors.MediumPurple,
				"mediumseagreen" => Colors.MediumSeaGreen,
				"mediumslateblue" => Colors.MediumSlateBlue,
				"mediumspringgreen" => Colors.MediumSpringGreen,
				"mediumturquoise" => Colors.MediumTurquoise,
				"mediumvioletred" => Colors.MediumVioletRed,
				"midnightblue" => Colors.MidnightBlue,
				"mintcream" => Colors.MintCream,
				"mistyrose" => Colors.MistyRose,
				"moccasin" => Colors.Moccasin,
				"navajowhite" => Colors.NavajoWhite,
				"navy" => Colors.Navy,
				"oldlace" => Colors.OldLace,
				"olive" => Colors.Olive,
				"olivedrab" => Colors.OliveDrab,
				"orange" => Colors.Orange,
				"orangered" => Colors.OrangeRed,
				"orchid" => Colors.Orchid,
				"palegoldenrod" => Colors.PaleGoldenrod,
				"palegreen" => Colors.PaleGreen,
				"paleturquoise" => Colors.PaleTurquoise,
				"palevioletred" => Colors.PaleVioletRed,
				"papayawhip" => Colors.PapayaWhip,
				"peachpuff" => Colors.PeachPuff,
				"peru" => Colors.Peru,
				"pink" => Colors.Pink,
				"plum" => Colors.Plum,
				"powderblue" => Colors.PowderBlue,
				"purple" => Colors.Purple,
				"red" => Colors.Red,
				"rosybrown" => Colors.RosyBrown,
				"royalblue" => Colors.RoyalBlue,
				"saddlebrown" => Colors.SaddleBrown,
				"salmon" => Colors.Salmon,
				"sandybrown" => Colors.SandyBrown,
				"seagreen" => Colors.SeaGreen,
				"seashell" => Colors.SeaShell,
				"sienna" => Colors.Sienna,
				"silver" => Colors.Silver,
				"skyblue" => Colors.SkyBlue,
				"slateblue" => Colors.SlateBlue,
				"slategray" => Colors.SlateGray,
				"slategrey" => Colors.SlateGrey,
				"snow" => Colors.Snow,
				"springgreen" => Colors.SpringGreen,
				"steelblue" => Colors.SteelBlue,
				"tan" => Colors.Tan,
				"teal" => Colors.Teal,
				"thistle" => Colors.Thistle,
				"tomato" => Colors.Tomato,
				"transparent" => Colors.Transparent,
				"turquoise" => Colors.Turquoise,
				"violet" => Colors.Violet,
				"wheat" => Colors.Wheat,
				"white" => Colors.White,
				"whitesmoke" => Colors.WhiteSmoke,
				"yellow" => Colors.Yellow,
				"yellowgreen" => Colors.YellowGreen,
				_ => null
			};
		}
	}
}
